language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies and module
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements.testing.txt
  - pip install -e .

# command to run tests
script:
  - pytest
