version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:2.7
      - image: circleci/python:3
      - image: circleci/python:3.3
      - image: circleci/python:3.4
      - image: circleci/python:3.5
      - image: circleci/python:3.6
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt --user
            pip install -r requirements.testing.txt --user
        
      # run tests!
      - run:
          name: run tests
          command: |
            python -m tox
          # when: on_success
          # command: |
          #   python -m py.test --cov-report xml --cov=herepy
          #   python -m codecov
